init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - nodejs_version: 4
  - nodejs_version: 6

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --force

test_script:
  - node --version && npm --version
  - npm test

# Don't actually build.
build: off

matrix:
  fast_finish: true
