init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - nodejs_version: 7
  - nodejs_version: 4
  - nodejs_version: 6

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - set PATH=%APPDATA%\npm;%PATH%

test_script:
  - node --version && yarn --version
  - yarn test

# Don't actually build.
build: off

matrix:
  fast_finish: true
