// flow-typed signature: f67e97326be92c29e62e6a5247d810d5
// flow-typed version: <<STUB>>/del-cli_v^1.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'del-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'del-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'del-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'del-cli/cli.js' {
  declare module.exports: $Exports<'del-cli/cli'>;
}
