// flow-typed signature: d6a22fd4935df73e772073f37f4781b2
// flow-typed version: <<STUB>>/eslint-config-simenb-base_v^12.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-simenb-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-simenb-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-simenb-base/additions' {
  declare module.exports: any;
}

declare module 'eslint-config-simenb-base/legacy-additions' {
  declare module.exports: any;
}

declare module 'eslint-config-simenb-base/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-simenb-base/overrides' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-simenb-base/additions.js' {
  declare module.exports: $Exports<'eslint-config-simenb-base/additions'>;
}
declare module 'eslint-config-simenb-base/index' {
  declare module.exports: $Exports<'eslint-config-simenb-base'>;
}
declare module 'eslint-config-simenb-base/index.js' {
  declare module.exports: $Exports<'eslint-config-simenb-base'>;
}
declare module 'eslint-config-simenb-base/legacy-additions.js' {
  declare module.exports: $Exports<'eslint-config-simenb-base/legacy-additions'>;
}
declare module 'eslint-config-simenb-base/legacy.js' {
  declare module.exports: $Exports<'eslint-config-simenb-base/legacy'>;
}
declare module 'eslint-config-simenb-base/overrides.js' {
  declare module.exports: $Exports<'eslint-config-simenb-base/overrides'>;
}
